<?php

namespace App\Models;

use CodeIgniter\Model;

class ReferenceDataModel extends Model
{
    public function getJenjangPendidikan()
    {
        $jenjangPendidikan = [
            'tk'       => 'Taman Kanak-kanak (TK)',
            'sd'       => 'Sekolah Dasar (SD)',
            'smp'      => 'Sekolah Menengah Pertama (SMP)',
            'sma-smk'  => 'Sekolah Menengah Atas / SMK (SMA/SMK)',
            'd1'       => 'Diploma 1 (D1)',
            'd2'       => 'Diploma 2 (D2)',
            'd3'       => 'Diploma 3 (D3)',
            'd4'       => 'Diploma 4 (D4)',
            's1'       => 'Sarjana (S1)',
            's2'       => 'Magister (S2)',
            's3'       => 'Doktor (S3)',
        ];

        return $jenjangPendidikan;
    }

    public function getJurusanProfesi()
    {
        $jurusanProfesi = [
            'dokter' => 'Dokter',
            'dokter-gigi' => 'Dokter Gigi',
            'bidan-vokasi' => 'Bidan Vokasi',
            'bidan-vokasi-level-5' => 'Bidan Vokasi Level 5',
            'bidan-vokasi-level-6' => 'Bidan Vokasi Level 6',
            'bidan-profesi' => 'Bidan Profesi',
            'perawat-vokasi' => 'Perawat Vokasi',
            'ners' => 'Ners',
            'ners-spesialis-keperawatan-komunitas' => 'Ners Spesialis Keperawatan Komunitas',
            'ners-spesialis-keperawatan-anak' => 'Ners Spesialis Keperawatan Anak',
            'ners-spesialis-keperawatan-maternitas' => 'Ners Spesialis Keperawatan Maternitas',
            'ners-spesialis-keperawatan-medikal-bedah' => 'Ners Spesialis Keperawatan Medikal Bedah',
            'ners-spesialis-keperawatan-geriatri' => 'Ners Spesialis Keperawatan Geriatri',
            'ners-spesialis-keperawatan-jiwa' => 'Ners Spesialis Keperawatan Jiwa',
            'ners-spesialis-keperawatan-onkologi' => 'Ners Spesialis Keperawatan Onkologi',
            'ners-spesialis-keperawatan-kardiovaskuler' => 'Ners Spesialis Keperawatan Kardiovaskuler',
            'ners-spesialis-keperawatan-gawat-darurat-kritis' => 'Ners Spesialis Keperawatan Gawat Darurat Kritis',
            'perawat-vokasi-level-5' => 'Perawat Vokasi Level 5',
            'perawat-vokasi-level-6' => 'Perawat Vokasi Level 6',
            'tenaga-sanitasi-lingkungan' => 'Tenaga Sanitasi Lingkungan',
            'tenaga-sanitasi-lingkungan-level-5' => 'Tenaga Sanitasi Lingkungan Level 5',
            'tenaga-sanitasi-lingkungan-level-6' => 'Tenaga Sanitasi Lingkungan Level 6',
            'tenaga-kesehatan-masyarakat' => 'Tenaga Kesehatan Masyarakat',
            'tenaga-kesehatan-masyarakat-level-7' => 'Tenaga Kesehatan Masyarakat Level 7',
            'tenaga-vokasi-farmasi' => 'Tenaga Vokasi Farmasi',
            'tenaga-vokasi-farmasi-level-5' => 'Tenaga Vokasi Farmasi Level 5',
            'tenaga-vokasi-farmasi-level-6' => 'Tenaga Vokasi Farmasi Level 6',
            'tenaga-vokasi-analis-farmasi-dan-makanan-level-5' => 'Tenaga Vokasi Analis Farmasi dan Makanan Level 5',
            'nutrisionis' => 'Nutrisionis',
            'nutrisionis-level-5' => 'Nutrisionis Level 5',
            'nutrisionis-level-6' => 'Nutrisionis Level 6',
            'nutrisionis-level-8' => 'Nutrisionis Level 8',
            'dietisien' => 'Dietisien',
            'tenaga-teknologi-laboratorium-medik' => 'Tenaga Teknologi Laboratorium Medik',
            'tenaga-teknologi-laboratorium-medik-level-5' => 'Tenaga Teknologi Laboratorium Medik Level 5',
            'tenaga-teknologi-laboratorium-medik-level-6' => 'Tenaga Teknologi Laboratorium Medik Level 6',
            'apoteker' => 'Apoteker',
            'apoteker-spesialis' => 'Apoteker Spesialis',
            'psikolog-klinis' => 'Psikolog Klinis',
            'fisioterapis' => 'Fisioterapis',
            'fisioterapis-level-5' => 'Fisioterapis Level 5',
            'fisioterapis-level-6' => 'Fisioterapis Level 6',
            'terapis-okupasional' => 'Terapis Okupasional',
            'terapis-okupasional-level-5' => 'Terapis Okupasional Level 5',
            'terapis-okupasional-level-6' => 'Terapis Okupasional Level 6',
            'terapis-wicara' => 'Terapis Wicara',
            'terapis-wicara-level-5' => 'Terapis Wicara Level 5',
            'terapis-wicara-level-6' => 'Terapis Wicara Level 6',
            'akupunktur-terapis' => 'Akupunktur Terapis',
            'akupunktur-level-5' => 'Akupunktur Level 5',
            'akupunktur-level-6' => 'Akupunktur Level 6',
            'perekam-medis-informasi-kesehatan' => 'Perekam Medis dan Informasi Kesehatan',
            'perekam-medis-informasi-kesehatan-level-5' => 'Perekam Medis dan Informasi Kesehatan Level 5',
            'perekam-medis-informasi-kesehatan-level-6' => 'Perekam Medis dan Informasi Kesehatan Level 6',
            'teknisi-kardiovaskuler' => 'Teknisi Kardiovaskuler',
            'teknisi-kardiovaskuler-level-5' => 'Teknisi Kardiovaskuler Level 5',
            'teknisi-pelayanan-darah' => 'Teknisi Pelayanan Darah',
            'teknisi-pelayanan-darah-level-5' => 'Teknisi Pelayanan Darah Level 5',
            'refraksionis-optisien-optometris' => 'Refraksionis Optisien/ Optometris',
            'optometris-level-5' => 'Optometris Level 5',
            'optometris-level-6' => 'Optometris Level 6',
            'teknisi-gigi' => 'Teknisi Gigi',
            'teknisi-gigi-level-5' => 'Teknisi Gigi Level 5',
            'penata-anestesi' => 'Penata Anestesi',
            'penata-anestesi-level-5' => 'Penata Anestesi Level 5',
            'penata-anestesi-level-6' => 'Penata Anestesi Level 6',
            'terapis-gigi-dan-mulut' => 'Terapis Gigi dan Mulut',
            'terapis-gigi-dan-mulut-level-5' => 'Terapis Gigi dan Mulut Level 5',
            'terapis-gigi-dan-mulut-level-6' => 'Terapis Gigi dan Mulut Level 6',
            'audiologis' => 'Audiologis',
            'audiologis-level-5' => 'Audiologis Level 5',
            'radiografer' => 'Radiografer',
            'radiografer-level-5' => 'Radiografer Level 5',
            'radiografer-level-6' => 'Radiografer Level 6',
            'radiografer-level-8' => 'Radiografer Level 8',
            'elektromedis' => 'Elektromedis',
            'elektromedis-level-5' => 'Elektromedis Level 5',
            'elektromedis-level-6' => 'Elektromedis Level 6',
            'elektromedis-level-8' => 'Elektromedis Level 8',
            'fisikawan-medik' => 'Fisikawan Medik',
            'ortotik-prostetik' => 'Ortotik Prostetik',
            'ortotik-prostetik-level-5' => 'Ortotik Prostetik Level 5',
            'ortotik-prostetik-level-6' => 'Ortotik Prostetik Level 6',
            'ortotik-prostetik-level-7' => 'Ortotik Prostetik Level 7',
            'tenaga-kesehatan-tradisional-ramuan-jamu' => 'Tenaga Kesehatan Tradisional Ramuan Jamu',
            'tenaga-kesehatan-tradisional-ramuan-jamu-level-5' => 'Tenaga Kesehatan Tradisional Ramuan Jamu Level 5',
            'tenaga-kesehatan-tradisional-keterampilan' => 'Tenaga Kesehatan Tradisional Keterampilan',
            'tenaga-kesehatan-tradisional-interkontinental' => 'Tenaga Kesehatan Tradisional Interkontinental',
            'tenaga-kesehatan-tradisional-interkontinental-level-6' => 'Tenaga Kesehatan Tradisional Interkontinental Level 6',
            'epidemiolog-kesehatan' => 'Epidemiolog Kesehatan',
            'epidemiolog-kesehatan-level-5' => 'Epidemiolog Kesehatan Level 5',
            'epidemiolog-kesehatan-level-6' => 'Epidemiolog Kesehatan Level 6',
            'epidemiolog-kesehatan-level-7' => 'Epidemiolog Kesehatan Level 7',
            'pembimbing-kesehatan-kerja' => 'Pembimbing Kesehatan Kerja',
            'pembimbing-kesehatan-kerja-level-7' => 'Pembimbing Kesehatan Kerja Level 7',
            'tenaga-promosi-kesehatan-dan-ilmu-perilaku' => 'Tenaga Promosi Kesehatan dan Ilmu Perilaku',
            'tenaga-promosi-kesehatan-dan-ilmu-perilaku-level-5' => 'Tenaga Promosi Kesehatan dan Ilmu Perilaku Level 5',
            'tenaga-promosi-kesehatan-dan-ilmu-perilaku-level-6' => 'Tenaga Promosi Kesehatan dan Ilmu Perilaku Level 6',
            'tenaga-promosi-kesehatan-dan-ilmu-perilaku-level-7' => 'Tenaga Promosi Kesehatan dan Ilmu Perilaku Level 7',
            'entomolog-kesehatan' => 'Entomolog Kesehatan',
            'entomolog-kesehatan-level-5' => 'Entomolog Kesehatan Level 5',
            'entomolog-kesehatan-level-6' => 'Entomolog Kesehatan Level 6',
            'tenaga-kesehatan-tradisional-pengobat-tradisional' => 'Tenaga Kesehatan Tradisional Pengobat Tradisional',
            'tenaga-kesehatan-tradisional-pengobat-tradisional-level-5' => 'Tenaga Kesehatan Tradisional Pengobat Tradisional Level 5',
            'tenaga-kesehatan-tradisional-pengobat-tradisional-level-6' => 'Tenaga Kesehatan Tradisional Pengobat Tradisional Level 6',
            'tenaga-administratif-dan-kebijakan-kesehatan' => 'Tenaga Administratif dan Kebijakan Kesehatan',
            'dokter-spesialis-penyakit-dalam' => 'Dokter Spesialis Penyakit Dalam',
            'dokter-spesialis-obstetri-ginekologi' => 'Dokter Spesialis Obstetri dan Ginekologi',
            'dokter-spesialis-anak' => 'Dokter Spesialis Anak',
            'dokter-spesialis-bedah' => 'Dokter Spesialis Bedah',
            'dokter-spesialis-radiologi' => 'Dokter Spesialis Radiologi',
            'dokter-spesialis-anestesiologi' => 'Dokter Spesialis Anestesiologi dan Terapi Intensif',
            'dokter-spesialis-patologi-klinik' => 'Dokter Spesialis Patologi Klinik',
            'dokter-spesialis-patologi-anatomi' => 'Dokter Spesialis Patologi Anatomi',
            'dokter-spesialis-rehabilitasi-medik' => 'Dokter Spesialis Kedokteran Fisik dan Rehabilitasi Medik',
            'dokter-spesialis-okupasi' => 'Dokter Spesialis Kedokteran Okupasi',
            'dokter-spesialis-penerbangan' => 'Dokter Spesialis Kedokteran Penerbangan',
            'dokter-spesialis-gizi-klinik' => 'Dokter Spesialis Gizi Klinik',
            'dokter-spesialis-bedah-toraks-kardiovaskular' => 'Dokter Spesialis Bedah Toraks Kardiovaskular',
            'dokter-spesialis-mikrobiologi-klinik' => 'Dokter Spesialis Mikrobiologi Klinik',
            'dokter-spesialis-bedah-saraf' => 'Dokter Spesialis Bedah Saraf',
            'dokter-spesialis-kelautan' => 'Dokter Spesialis Kelautan',
            'dokter-spesialis-urologi' => 'Dokter Spesialis Urologi',
            'dokter-spesialis-dermatologi-venereologi-estetika' => 'Dokter Spesialis Dermatologi, Venereologi, dan Estetika',
            'dokter-spesialis-neurologi' => 'Dokter Spesialis Neurologi',
            'dokter-spesialis-orthopaedi-traumatologi' => 'Dokter Spesialis Orthopaedi dan Traumatologi',
            'dokter-spesialis-pulmonologi' => 'Dokter Spesialis Pulmonologi dan Kedokteran Respirasi',
            'dokter-spesialis-olahraga' => 'Dokter Spesialis Kedokteran Olahraga',
            'dokter-spesialis-psikiatri' => 'Dokter Spesialis Psikiatri',
            'dokter-spesialis-mata' => 'Dokter Spesialis Mata',
            'dokter-spesialis-nuklir-teranostik' => 'Dokter Spesialis Kedokteran Nuklir dan Teranostik Molekuler',
            'dokter-spesialis-telinga-hidung-tenggorok' => 'Dokter Spesialis Telinga Hidung Tenggorok Bedah Kepala dan Leher',
            'dokter-spesialis-bedah-plastik' => 'Dokter Spesialis Bedah Plastik dan Rekonstruksi Estetik',
            'dokter-spesialis-andrologi' => 'Dokter Spesialis Andrologi',
            'dokter-spesialis-jantung' => 'Dokter Spesialis Jantung dan Pembuluh Darah',
            'dokter-spesialis-forensik' => 'Dokter Spesialis Forensik dan Medikolegal',
            'dokter-spesialis-emergensi-medisin' => 'Dokter Spesialis Emergensi Medisin',
            'dokter-spesialis-onkologi-radiasi' => 'Dokter Spesialis Onkologi Radiasi',
            'dokter-spesialis-akupuntur-medik' => 'Dokter Spesialis Akupuntur Medik',
            'dokter-spesialis-bedah-anak' => 'Dokter Spesialis Bedah Anak',
            'dokter-spesialis-farmakologi-klinik' => 'Dokter Spesialis Farmakologi Klinik',
            'dokter-spesialis-parasitologi-klinik' => 'Dokter Spesialis Parasitologi Klinik',
            'dokter-spesialis-kedokteran-keluarga' => 'Dokter Spesialis Kedokteran Keluarga Layanan Primer',
            'dokter-gigi-spesialis-ortodonti' => 'Dokter Gigi Spesialis Ortodonti',
            'dokter-gigi-spesialis-bedah-mulut' => 'Dokter Gigi Spesialis Bedah Mulut dan Maksilofasial',
            'dokter-gigi-spesialis-anak' => 'Dokter Gigi Spesialis Kedokteran Gigi Anak',
            'dokter-gigi-spesialis-konservasi-gigi' => 'Dokter Gigi Spesialis Konservasi Gigi',
            'dokter-gigi-spesialis-prostodonsia' => 'Dokter Gigi Spesialis Prostodonsia',
            'dokter-gigi-spesialis-penyakit-mulut' => 'Dokter Gigi Spesialis Penyakit Mulut',
            'dokter-gigi-spesialis-periodonsia' => 'Dokter Gigi Spesialis Periodonsia',
            'dokter-gigi-spesialis-radiologi' => 'Dokter Gigi Spesialis Radiologi Kedokteran Gigi',
            'dokter-gigi-spesialis-odontologi-forensik' => 'Dokter Gigi Spesialis Odontologi Forensik',
            'dokter-gigi-spesialis-patologi-mulut' => 'Dokter Gigi Spesialis Patologi Mulut dan Maksilofasial',
            
            // Lainnya
            'lainnya'               => 'Lainnya'
        ];

        return $jurusanProfesi;
    }
}
